# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cc32831b6ceb0b94b940abd57941ebd7b17412552b50bb098e42208fac809043ad7f77f643556b56f6a0fc76036132b28f1d31dd5f44ac8b1d73b099746616

test:
  secret_key_base: 5c117c5135c891bbf74155f081039b15a5fa033f5ad3eea072700266909871d4e575ab7c9d3cb7ab14624561705d162110266c2843c95ca7716fb1ce82e5a9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
